version: '3'
services:

  database:
    image: dpage/pgadmin4
    container_name: pgadmin4
    network_mode: "host"
    ports:
      - "8085:8085"
    expose: 
      - 5432
    environment:
          PGADMIN_DEFAULT_EMAIL   : user@dom.tld
          PGADMIN_DEFAULT_PASSWORD: secret-word
          PGADMIN_LISTEN_ADDRESS  : 127.0.0.1
          PGADMIN_LISTEN_PORT     : 8085
